# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
