# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_books', '0002_auto_20180116_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
